version: "3.7"

services:
  db:
    image: mdillon/postgis:11-alpine # Don't need topology/fuzzymatch/tiger_geocoder extensions; Fix later
    restart: always
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  server:
    build: .
    environment:
      - PG_PORT=5432
      - PG_HOST=db
      - PG_DB=scheduler
      - PG_USER=docker
      - PG_PASSWORD=docker
    volumes:
      # Sync local changes so that hot reloading will work in the container
      - .:/app
    command: ["sh", "wait-for-postgres.sh", "./main.go"]
    links:
      - db
    ports: 
      - "8080:8080"
      - "5001:5001"
