// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobufs/reservations.proto

package reservations

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// Add not null constraints?
type Book struct {
	Isbn    string  `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Lat     float32 `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng     float32 `protobuf:"fixed32,3,opt,name=lng,proto3" json:"lng,omitempty"`
	Library string  `protobuf:"bytes,4,opt,name=library,proto3" json:"library,omitempty"`
	// ISO 4217
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *Book) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Book) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *Book) GetLibrary() string {
	if m != nil {
		return m.Library
	}
	return ""
}

func (m *Book) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetAllBooksRes struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllBooksRes) Reset()         { *m = GetAllBooksRes{} }
func (m *GetAllBooksRes) String() string { return proto.CompactTextString(m) }
func (*GetAllBooksRes) ProtoMessage()    {}
func (*GetAllBooksRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{2}
}

func (m *GetAllBooksRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllBooksRes.Unmarshal(m, b)
}
func (m *GetAllBooksRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllBooksRes.Marshal(b, m, deterministic)
}
func (m *GetAllBooksRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllBooksRes.Merge(m, src)
}
func (m *GetAllBooksRes) XXX_Size() int {
	return xxx_messageInfo_GetAllBooksRes.Size(m)
}
func (m *GetAllBooksRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllBooksRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllBooksRes proto.InternalMessageInfo

func (m *GetAllBooksRes) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type GetBookReq struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookReq) Reset()         { *m = GetBookReq{} }
func (m *GetBookReq) String() string { return proto.CompactTextString(m) }
func (*GetBookReq) ProtoMessage()    {}
func (*GetBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{3}
}

func (m *GetBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookReq.Unmarshal(m, b)
}
func (m *GetBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookReq.Marshal(b, m, deterministic)
}
func (m *GetBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookReq.Merge(m, src)
}
func (m *GetBookReq) XXX_Size() int {
	return xxx_messageInfo_GetBookReq.Size(m)
}
func (m *GetBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookReq proto.InternalMessageInfo

func (m *GetBookReq) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

type ReturnBookReq struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnBookReq) Reset()         { *m = ReturnBookReq{} }
func (m *ReturnBookReq) String() string { return proto.CompactTextString(m) }
func (*ReturnBookReq) ProtoMessage()    {}
func (*ReturnBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{4}
}

func (m *ReturnBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnBookReq.Unmarshal(m, b)
}
func (m *ReturnBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnBookReq.Marshal(b, m, deterministic)
}
func (m *ReturnBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnBookReq.Merge(m, src)
}
func (m *ReturnBookReq) XXX_Size() int {
	return xxx_messageInfo_ReturnBookReq.Size(m)
}
func (m *ReturnBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnBookReq proto.InternalMessageInfo

func (m *ReturnBookReq) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

type AddBookReq struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookReq) Reset()         { *m = AddBookReq{} }
func (m *AddBookReq) String() string { return proto.CompactTextString(m) }
func (*AddBookReq) ProtoMessage()    {}
func (*AddBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{5}
}

func (m *AddBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookReq.Unmarshal(m, b)
}
func (m *AddBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookReq.Marshal(b, m, deterministic)
}
func (m *AddBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookReq.Merge(m, src)
}
func (m *AddBookReq) XXX_Size() int {
	return xxx_messageInfo_AddBookReq.Size(m)
}
func (m *AddBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookReq proto.InternalMessageInfo

func (m *AddBookReq) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type DeleteBookReq struct {
	Isbn                 string   `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookReq) Reset()         { *m = DeleteBookReq{} }
func (m *DeleteBookReq) String() string { return proto.CompactTextString(m) }
func (*DeleteBookReq) ProtoMessage()    {}
func (*DeleteBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{6}
}

func (m *DeleteBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookReq.Unmarshal(m, b)
}
func (m *DeleteBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookReq.Marshal(b, m, deterministic)
}
func (m *DeleteBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookReq.Merge(m, src)
}
func (m *DeleteBookReq) XXX_Size() int {
	return xxx_messageInfo_DeleteBookReq.Size(m)
}
func (m *DeleteBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookReq proto.InternalMessageInfo

func (m *DeleteBookReq) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

type ReserveBookReq struct {
	Isbn string `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	// Start and End times are ISO8601 format
	StartDate            string   `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveBookReq) Reset()         { *m = ReserveBookReq{} }
func (m *ReserveBookReq) String() string { return proto.CompactTextString(m) }
func (*ReserveBookReq) ProtoMessage()    {}
func (*ReserveBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{7}
}

func (m *ReserveBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveBookReq.Unmarshal(m, b)
}
func (m *ReserveBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveBookReq.Marshal(b, m, deterministic)
}
func (m *ReserveBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveBookReq.Merge(m, src)
}
func (m *ReserveBookReq) XXX_Size() int {
	return xxx_messageInfo_ReserveBookReq.Size(m)
}
func (m *ReserveBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveBookReq proto.InternalMessageInfo

func (m *ReserveBookReq) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *ReserveBookReq) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *ReserveBookReq) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type CheckoutBookReq struct {
	Isbn string `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	// Start and End times are ISO8601 format
	StartDate            string   `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutBookReq) Reset()         { *m = CheckoutBookReq{} }
func (m *CheckoutBookReq) String() string { return proto.CompactTextString(m) }
func (*CheckoutBookReq) ProtoMessage()    {}
func (*CheckoutBookReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{8}
}

func (m *CheckoutBookReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutBookReq.Unmarshal(m, b)
}
func (m *CheckoutBookReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutBookReq.Marshal(b, m, deterministic)
}
func (m *CheckoutBookReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutBookReq.Merge(m, src)
}
func (m *CheckoutBookReq) XXX_Size() int {
	return xxx_messageInfo_CheckoutBookReq.Size(m)
}
func (m *CheckoutBookReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutBookReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutBookReq proto.InternalMessageInfo

func (m *CheckoutBookReq) GetIsbn() string {
	if m != nil {
		return m.Isbn
	}
	return ""
}

func (m *CheckoutBookReq) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *CheckoutBookReq) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type SearchReq struct {
	Lat   float32 `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng   float32 `protobuf:"fixed32,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Range float32 `protobuf:"fixed32,3,opt,name=range,proto3" json:"range,omitempty"`
	// Start and End times are ISO8601 format
	StartDate            string   `protobuf:"bytes,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate              string   `protobuf:"bytes,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchReq) Reset()         { *m = SearchReq{} }
func (m *SearchReq) String() string { return proto.CompactTextString(m) }
func (*SearchReq) ProtoMessage()    {}
func (*SearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{9}
}

func (m *SearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReq.Unmarshal(m, b)
}
func (m *SearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReq.Marshal(b, m, deterministic)
}
func (m *SearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReq.Merge(m, src)
}
func (m *SearchReq) XXX_Size() int {
	return xxx_messageInfo_SearchReq.Size(m)
}
func (m *SearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReq proto.InternalMessageInfo

func (m *SearchReq) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *SearchReq) GetLng() float32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *SearchReq) GetRange() float32 {
	if m != nil {
		return m.Range
	}
	return 0
}

func (m *SearchReq) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *SearchReq) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

type SearchRes struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRes) Reset()         { *m = SearchRes{} }
func (m *SearchRes) String() string { return proto.CompactTextString(m) }
func (*SearchRes) ProtoMessage()    {}
func (*SearchRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_25f40a216b443982, []int{10}
}

func (m *SearchRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRes.Unmarshal(m, b)
}
func (m *SearchRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRes.Marshal(b, m, deterministic)
}
func (m *SearchRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRes.Merge(m, src)
}
func (m *SearchRes) XXX_Size() int {
	return xxx_messageInfo_SearchRes.Size(m)
}
func (m *SearchRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRes.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRes proto.InternalMessageInfo

func (m *SearchRes) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "reservations.Empty")
	proto.RegisterType((*Book)(nil), "reservations.Book")
	proto.RegisterType((*GetAllBooksRes)(nil), "reservations.GetAllBooksRes")
	proto.RegisterType((*GetBookReq)(nil), "reservations.GetBookReq")
	proto.RegisterType((*ReturnBookReq)(nil), "reservations.ReturnBookReq")
	proto.RegisterType((*AddBookReq)(nil), "reservations.AddBookReq")
	proto.RegisterType((*DeleteBookReq)(nil), "reservations.DeleteBookReq")
	proto.RegisterType((*ReserveBookReq)(nil), "reservations.ReserveBookReq")
	proto.RegisterType((*CheckoutBookReq)(nil), "reservations.CheckoutBookReq")
	proto.RegisterType((*SearchReq)(nil), "reservations.SearchReq")
	proto.RegisterType((*SearchRes)(nil), "reservations.SearchRes")
}

func init() {
	proto.RegisterFile("protobufs/reservations.proto", fileDescriptor_25f40a216b443982)
}

var fileDescriptor_25f40a216b443982 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xe5, 0x24, 0x6e, 0x94, 0x49, 0x7e, 0xf9, 0x95, 0x21, 0xa8, 0x8b, 0x9b, 0xa2, 0x68,
	0x8b, 0x50, 0x94, 0x43, 0x2d, 0x0a, 0x5c, 0x72, 0x2b, 0x14, 0xf5, 0x56, 0x09, 0xf7, 0x08, 0x1c,
	0xec, 0x64, 0x49, 0xa2, 0x9a, 0x75, 0x58, 0x6f, 0x2a, 0x55, 0xa8, 0x17, 0x5e, 0x81, 0x47, 0xe3,
	0x15, 0x90, 0x78, 0x0d, 0xb4, 0x63, 0xa7, 0xce, 0x3a, 0x26, 0x12, 0x07, 0x6e, 0xbb, 0xb3, 0x33,
	0x9f, 0xef, 0xce, 0x9f, 0x5d, 0xe8, 0x2f, 0x55, 0xa2, 0x93, 0x68, 0xf5, 0x29, 0xf5, 0x95, 0x48,
	0x85, 0xba, 0x09, 0xf5, 0x22, 0x91, 0xe9, 0x09, 0x99, 0xb1, 0xb3, 0x69, 0xf3, 0xfa, 0xb3, 0x24,
	0x99, 0xc5, 0xc2, 0x0f, 0x97, 0x0b, 0x3f, 0x94, 0x32, 0xd1, 0x9b, 0xbe, 0xbc, 0x09, 0xee, 0xdb,
	0xcf, 0x4b, 0x7d, 0xcb, 0x25, 0x34, 0x5e, 0x27, 0xc9, 0x35, 0x22, 0x34, 0x16, 0x69, 0x24, 0x99,
	0x33, 0x70, 0x86, 0xad, 0x80, 0xd6, 0xb8, 0x0f, 0xf5, 0x38, 0xd4, 0xac, 0x36, 0x70, 0x86, 0xb5,
	0xc0, 0x2c, 0xc9, 0x22, 0x67, 0xac, 0x9e, 0x5b, 0xe4, 0x0c, 0x19, 0x34, 0xe3, 0x45, 0xa4, 0x42,
	0x75, 0xcb, 0x1a, 0x14, 0xba, 0xde, 0x62, 0x0f, 0xdc, 0xa5, 0x5a, 0x4c, 0x04, 0x73, 0xc9, 0x3b,
	0xdb, 0xf0, 0x31, 0x74, 0x2f, 0x84, 0x3e, 0x8b, 0x63, 0xa3, 0x9a, 0x06, 0x22, 0xc5, 0x21, 0xb8,
	0x91, 0x59, 0x33, 0x67, 0x50, 0x1f, 0xb6, 0x4f, 0xf1, 0xc4, 0x4a, 0xcd, 0xb8, 0x05, 0x99, 0x03,
	0x1f, 0x00, 0x5c, 0x08, 0x4d, 0x16, 0xf1, 0xa5, 0xea, 0xc6, 0xfc, 0x18, 0xfe, 0x0b, 0x84, 0x5e,
	0x29, 0xb9, 0xcb, 0xe9, 0x25, 0xc0, 0xd9, 0x74, 0xba, 0xf6, 0x78, 0x06, 0x0d, 0x43, 0x27, 0x8f,
	0x6a, 0x75, 0x3a, 0x37, 0xe8, 0x73, 0x11, 0x0b, 0x2d, 0x76, 0xa1, 0x3f, 0x40, 0x37, 0xa0, 0xf8,
	0x5d, 0x5e, 0xd8, 0x87, 0x56, 0xaa, 0x43, 0xa5, 0xcf, 0x43, 0x2d, 0xa8, 0xba, 0xad, 0xa0, 0x30,
	0x98, 0x8a, 0x0a, 0x39, 0xa5, 0xb3, 0x7a, 0x56, 0xd1, 0x7c, 0xcb, 0x3f, 0xc2, 0xff, 0x6f, 0xe6,
	0x62, 0x72, 0x9d, 0xac, 0xf4, 0xbf, 0xc0, 0xdf, 0x41, 0xeb, 0x4a, 0x84, 0x6a, 0x32, 0x37, 0xe0,
	0xbc, 0xf7, 0xce, 0x56, 0xef, 0x6b, 0x45, 0xef, 0x7b, 0xe0, 0xaa, 0x50, 0xce, 0x44, 0x3e, 0x0f,
	0xd9, 0xc6, 0x96, 0x6f, 0xec, 0x90, 0x77, 0x6d, 0xf9, 0x57, 0x85, 0xfc, 0x5f, 0x0c, 0xc5, 0xe9,
	0x2f, 0x17, 0xda, 0x41, 0x71, 0x88, 0x57, 0xd0, 0xde, 0x18, 0x30, 0x7c, 0x68, 0x47, 0xd2, 0xd0,
	0x7b, 0x7d, 0xdb, 0x68, 0x0f, 0x24, 0x7f, 0xf0, 0xed, 0xc7, 0xcf, 0xef, 0xb5, 0x36, 0xb6, 0xfc,
	0x9b, 0xe7, 0x3e, 0x89, 0xe0, 0x3b, 0x68, 0xe6, 0x93, 0x87, 0x6c, 0x2b, 0x36, 0xef, 0x85, 0x57,
	0x71, 0x49, 0xce, 0x88, 0x85, 0xb8, 0x7f, 0xcf, 0xf2, 0xbf, 0x9a, 0x26, 0xdd, 0xe1, 0x25, 0xec,
	0x65, 0xe9, 0xe2, 0x81, 0x1d, 0x77, 0xdf, 0x03, 0xef, 0x0f, 0x07, 0x29, 0x47, 0xa2, 0x76, 0x10,
	0x0c, 0x35, 0xcd, 0x28, 0x97, 0xd0, 0xcc, 0xa7, 0xba, 0x7c, 0xc5, 0x62, 0xd8, 0xbd, 0xaa, 0x6a,
	0xf0, 0x1e, 0xd1, 0xba, 0xbc, 0xc8, 0x77, 0xec, 0x8c, 0xf0, 0x3d, 0x40, 0x31, 0xef, 0x78, 0x68,
	0x07, 0x5a, 0x2f, 0xa1, 0x9a, 0x7a, 0x48, 0xd4, 0x47, 0xa3, 0xad, 0xcc, 0x0d, 0x5c, 0xac, 0x7b,
	0x96, 0xd1, 0x4b, 0xfd, 0xb0, 0x9f, 0x50, 0x35, 0xfe, 0x98, 0xf0, 0x47, 0x1e, 0x2b, 0xe3, 0xf3,
	0x9f, 0x51, 0x18, 0x99, 0x39, 0x74, 0x36, 0x1f, 0x0c, 0x1e, 0xd9, 0xa4, 0xd2, 0x63, 0xaa, 0x16,
	0x7a, 0x4a, 0x42, 0x4f, 0xf8, 0xe3, 0x2d, 0xa1, 0x49, 0x1e, 0x6e, 0x94, 0x22, 0x80, 0xe2, 0xe3,
	0x29, 0x57, 0xcb, 0xfa, 0x92, 0xaa, 0x55, 0x38, 0xa9, 0xf4, 0xf9, 0x41, 0x45, 0x3a, 0x26, 0x78,
	0xec, 0x8c, 0xa2, 0x3d, 0xfa, 0xba, 0x5f, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x22, 0x55,
	0x48, 0x06, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReservationClient is the client API for Reservation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReservationClient interface {
	GetAllBooks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllBooksRes, error)
	GetBook(ctx context.Context, in *GetBookReq, opts ...grpc.CallOption) (*Book, error)
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchRes, error)
	AddBook(ctx context.Context, in *AddBookReq, opts ...grpc.CallOption) (*Empty, error)
	DeleteBook(ctx context.Context, in *DeleteBookReq, opts ...grpc.CallOption) (*Empty, error)
	ReserveBook(ctx context.Context, in *ReserveBookReq, opts ...grpc.CallOption) (*Empty, error)
	CheckoutBook(ctx context.Context, in *CheckoutBookReq, opts ...grpc.CallOption) (*Empty, error)
	ReturnBook(ctx context.Context, in *ReturnBookReq, opts ...grpc.CallOption) (*Empty, error)
}

type reservationClient struct {
	cc grpc.ClientConnInterface
}

func NewReservationClient(cc grpc.ClientConnInterface) ReservationClient {
	return &reservationClient{cc}
}

func (c *reservationClient) GetAllBooks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllBooksRes, error) {
	out := new(GetAllBooksRes)
	err := c.cc.Invoke(ctx, "/reservations.Reservation/GetAllBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationClient) GetBook(ctx context.Context, in *GetBookReq, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/reservations.Reservation/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationClient) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchRes, error) {
	out := new(SearchRes)
	err := c.cc.Invoke(ctx, "/reservations.Reservation/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationClient) AddBook(ctx context.Context, in *AddBookReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/reservations.Reservation/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationClient) DeleteBook(ctx context.Context, in *DeleteBookReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/reservations.Reservation/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationClient) ReserveBook(ctx context.Context, in *ReserveBookReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/reservations.Reservation/ReserveBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationClient) CheckoutBook(ctx context.Context, in *CheckoutBookReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/reservations.Reservation/CheckoutBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reservationClient) ReturnBook(ctx context.Context, in *ReturnBookReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/reservations.Reservation/ReturnBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReservationServer is the server API for Reservation service.
type ReservationServer interface {
	GetAllBooks(context.Context, *Empty) (*GetAllBooksRes, error)
	GetBook(context.Context, *GetBookReq) (*Book, error)
	Search(context.Context, *SearchReq) (*SearchRes, error)
	AddBook(context.Context, *AddBookReq) (*Empty, error)
	DeleteBook(context.Context, *DeleteBookReq) (*Empty, error)
	ReserveBook(context.Context, *ReserveBookReq) (*Empty, error)
	CheckoutBook(context.Context, *CheckoutBookReq) (*Empty, error)
	ReturnBook(context.Context, *ReturnBookReq) (*Empty, error)
}

// UnimplementedReservationServer can be embedded to have forward compatible implementations.
type UnimplementedReservationServer struct {
}

func (*UnimplementedReservationServer) GetAllBooks(ctx context.Context, req *Empty) (*GetAllBooksRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllBooks not implemented")
}
func (*UnimplementedReservationServer) GetBook(ctx context.Context, req *GetBookReq) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedReservationServer) Search(ctx context.Context, req *SearchReq) (*SearchRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedReservationServer) AddBook(ctx context.Context, req *AddBookReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBook not implemented")
}
func (*UnimplementedReservationServer) DeleteBook(ctx context.Context, req *DeleteBookReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (*UnimplementedReservationServer) ReserveBook(ctx context.Context, req *ReserveBookReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveBook not implemented")
}
func (*UnimplementedReservationServer) CheckoutBook(ctx context.Context, req *CheckoutBookReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckoutBook not implemented")
}
func (*UnimplementedReservationServer) ReturnBook(ctx context.Context, req *ReturnBookReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnBook not implemented")
}

func RegisterReservationServer(s *grpc.Server, srv ReservationServer) {
	s.RegisterService(&_Reservation_serviceDesc, srv)
}

func _Reservation_GetAllBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).GetAllBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.Reservation/GetAllBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).GetAllBooks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reservation_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.Reservation/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).GetBook(ctx, req.(*GetBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reservation_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.Reservation/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reservation_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.Reservation/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).AddBook(ctx, req.(*AddBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reservation_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.Reservation/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).DeleteBook(ctx, req.(*DeleteBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reservation_ReserveBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).ReserveBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.Reservation/ReserveBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).ReserveBook(ctx, req.(*ReserveBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reservation_CheckoutBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).CheckoutBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.Reservation/CheckoutBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).CheckoutBook(ctx, req.(*CheckoutBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reservation_ReturnBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnBookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReservationServer).ReturnBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reservations.Reservation/ReturnBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReservationServer).ReturnBook(ctx, req.(*ReturnBookReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reservation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reservations.Reservation",
	HandlerType: (*ReservationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllBooks",
			Handler:    _Reservation_GetAllBooks_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _Reservation_GetBook_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Reservation_Search_Handler,
		},
		{
			MethodName: "AddBook",
			Handler:    _Reservation_AddBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Reservation_DeleteBook_Handler,
		},
		{
			MethodName: "ReserveBook",
			Handler:    _Reservation_ReserveBook_Handler,
		},
		{
			MethodName: "CheckoutBook",
			Handler:    _Reservation_CheckoutBook_Handler,
		},
		{
			MethodName: "ReturnBook",
			Handler:    _Reservation_ReturnBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobufs/reservations.proto",
}
